[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/check-membership",
    "pallets/compounding-interest",
    "pallets/currency-imbalances",
    "pallets/simple-crowdfund",
    "pallets/reservable-currency",
    "runtime",
]
[profile.release]
panic = "unwind"
